export * from './event-details/event-details.component'
export * from './event-details//event-route-activator.service'
export * from './event-details/create-session.component'
export * from './event-details/session-list.component'
export * from './shared/duration.pipe'